# Generated by Django 2.2.2 on 2019-07-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190705_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_subscriber',
            field=models.BooleanField(default=False, verbose_name='是否发布给订阅者'),
        ),
    ]
