# Generated by Django 2.2.2 on 2019-07-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_send_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='send_subscriber',
            field=models.BooleanField(default=False, verbose_name='已经发布给订阅者'),
        ),
    ]
