# Generated by Django 2.2.2 on 2019-08-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190829_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='回复对象'),
        ),
    ]
