# Generated by Django 2.2.2 on 2019-08-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190829_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
