# Generated by Django 2.2.2 on 2019-07-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_delete_sidebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订阅',
                'verbose_name_plural': '订阅',
            },
        ),
    ]
